import { Schema } from "effect"
import { TenantId, TicketEventId, TicketId, UserId } from "#ids"

/**
 * In-flight notification. One row per (recipient × event).
 *
 * Generated by the TicketEntity when an event fires and matching subscribers
 * exist (see ARCHITECTURE.md → Participants). Delivery (email / webhook /
 * in-app stream) lives in Phase 8 — for now we just persist + count unread.
 */

export const NotificationChannel = Schema.Literals(["in_app", "email", "webhook"])
export type NotificationChannel = typeof NotificationChannel.Type

export class Notification extends Schema.Class<Notification>("Notification")({
  id: Schema.NonEmptyString,
  tenantId: TenantId,
  recipientId: UserId,
  ticketId: TicketId,
  /** The TicketEvent that triggered this notification. */
  eventId: TicketEventId,
  channel: NotificationChannel,
  /** Short, denormalized title for fast list rendering (no join needed). */
  title: Schema.NonEmptyString,
  /** Optional body — null for compact-only notifications. */
  body: Schema.NullOr(Schema.String),
  createdAt: Schema.DateTimeUtcFromString,
  readAt: Schema.NullOr(Schema.DateTimeUtcFromString),
  /** Set when the channel layer has dispatched (email sent, webhook 2xx, etc.). */
  deliveredAt: Schema.NullOr(Schema.DateTimeUtcFromString),
}) {}
